version: 0.2

# La sección "phases" define los pasos de compilación
phases:
  # Fase de instalación: Instala las dependencias y configura el entorno
  install:
    runtime-versions:
      ruby: 3.2.2
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - gem install bundler
      - bundle install --jobs $(nproc) --retry 3
      #- rbenv install 3.2.0  # Instala ruby-3.2.0 si no está instalado
      #- rbenv local 3.2.0    # Configura la versión de Ruby para este proyecto
      #- bundle install

  # Fase de compilación: Construye la aplicación Rails
  build:
    commands:
      - echo "Building application..."
      - bundle exec rake assets:precompile
      - bundle exec rake db:create db:migrate

  # Fase post-build: Ejecuta tareas posteriores a la compilación
  post_build:
    commands:
      - echo "Executing integration tests..."
      - bundle exec rake test
      - echo "Success compilation..."

# La sección "artifacts" define los artefactos de salida
artifacts:
  files:
    - '**/*'
  name: poc-bloc-$(date +%Y-%m-%d)
